/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 */
package com.eurodisney.test.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.List;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.eurodisney.test.domain.Department;
import com.eurodisney.test.domain.Department_;
import com.eurodisney.test.repository.support.SearchParameters;

/**
 * Integration test on DepartmentRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class DepartmentRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(DepartmentRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private DepartmentRepository departmentRepository;

    @Inject
    private DepartmentGenerator departmentGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Department department = departmentGenerator.getDepartment();
        department.setId(3);

        // add it to a Set before saving (force equals/hashcode)
        Set<Department> set = newHashSet(department, department);
        assertThat(set).hasSize(1);

        departmentRepository.save(department);
        entityManager.flush();

        // reload it from cache and check equality
        Department model = new Department();
        model.setId(department.getId());
        assertThat(department).isEqualTo(departmentRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // since you use a business key, equality must be preserved.
        assertThat(department).isEqualTo(departmentRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithExplicitNullPropertySelector() {
        Department department = departmentGenerator.getDepartment();

        // add it to a Set before saving (force equals/hashcode)
        Set<Department> set = newHashSet(department, department);
        assertThat(set).hasSize(1);

        // explicitly set toOne relationship to null
        department.setIdDisney(null);

        departmentRepository.save(department);
        entityManager.flush();

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters searchParameters = new SearchParameters() //
                .caseInsensitive() //
                .anywhere() //
                .property(Department_.idDisney, (Object) null);

        List<Department> elements = departmentRepository.find(searchParameters);
        assertThat(elements).isNotEmpty();
        for (Department element : elements) {
            assertThat(element.getIdDisney()).isNull();
        }
    }
}