/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.eurodisney.test.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Disney.class)
public abstract class Disney_ {

    // Raw attributes
    public static volatile SingularAttribute<Disney, Integer> id;
    public static volatile SingularAttribute<Disney, String> name;
    public static volatile SingularAttribute<Disney, String> realname;
}