/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.eurodisney.test.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.eurodisney.test.domain.Disney;
import com.eurodisney.test.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link Disney} 
 */
@Named
@Singleton
public class DisneyRepository extends GenericRepository<Disney, Integer> {

    public DisneyRepository() {
        super(Disney.class);
    }

    @Override
    public Disney getNew() {
        return new Disney();
    }

    @Override
    public Disney getNewWithDefaults() {
        return getNew().withDefaults();
    }
}